### ISSUE TITLE
how to dissable HOLD and WP pins in SPI flash

### ISSUE THREAD

**Issue by nagarathna321** [lllucius/esp32_extflash#1]
HI I am working with esp32 and  IS25LP016D 16 MB flash I could read and write properly with normal with HOLD and Write Protect pin But now I want to avoide the HOLD and WP pins . I gave -1 for both now the Flash is not able to intialize please any one can help me .

**Comment by lllucius** [comment]
Can you show me your init parms?  Any chance you could bundle your source and attach it?  I can try it here then.
